name       : vcmi
version    : 0.98
release    : 1
source     :
    - https://github.com/vcmi/vcmi/archive/0.98.tar.gz : 5a58ab487e48d3f42bfbbec6b6f13f8083f9499ae2fa2bd75285bda848984d90
license    : GPL-2.0
component  : games.strategy
summary    : Open-source engine for Heroes of Might and Magic III
description: |
    VCMI is an open-source implementation of the Heroes III engine, giving it new and extended possibilities. To use VCMI you need to own original data files.
builddeps  :
    - pkgconfig(egl)
    - pkgconfig(libavformat)
    - pkgconfig(Qt5Core)
    - pkgconfig(sdl2)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(zlib)
    - libboost-devel
    - libstdc++
rundeps    :
    - innoextract
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
    rm -v $installdir/%libdir%/*.a