name       : vcmi
version    : 0.99
release    : 17
source     :
    - git|https://github.com/vcmi/vcmi.git : cc75b859d49c6bf43a1f55769b1a6aad5290d851
license    :
    - CC-BY-SA-4.0
    - GPL-2.0-or-later
component  : games.strategy
summary    : Open-source engine for Heroes of Might and Magic III
description: |
    VCMI is an open-source implementation of the Heroes III engine, giving it new and extended possibilities. To use VCMI you need to own original data files.
optimize   :
    - runpath
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(egl)
    - pkgconfig(libavformat)
    - pkgconfig(minizip)
    - libboost-devel
rundeps    :
    - innoextract
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON \
           -DCMAKE_SKIP_RPATH=FALSE \
           -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE \
           -DCMAKE_INSTALL_RPATH=%libdir%/vcmi
build      : |
    %ninja_build
install    : |
    %ninja_install
