name       : vcmi
version    : 0.99
release    : 9
source     :
    - https://github.com/vcmi/vcmi/archive/0.99.tar.gz : b7f2459d7e054c8bdcf419cbb80040e751d3dbb06dc1113ac28f7365930f902e
license    :
    - CC-BY-SA-4.0
    - GPL-2.0-or-later
component  : games.strategy
summary    : Open-source engine for Heroes of Might and Magic III
description: |
    VCMI is an open-source implementation of the Heroes III engine, giving it new and extended possibilities. To use VCMI you need to own original data files.
builddeps  :
    - pkgconfig(egl)
    - pkgconfig(libavformat)
    - pkgconfig(Qt5Core)
    - pkgconfig(sdl2)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(zlib)
    - libboost-devel
rundeps    :
    - innoextract
setup      : |
    %patch -p1 < $pkgfiles/boost-1.66.patch

    %cmake -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=OFF .
build      : |
    %make
install    : |
    %make_install
    rm -v $installdir/%libdir%/*.a
